### PR TITLE
Added Support for Generating Protobuf Schema From POJO Definition

### PR DESCRIPTION
**Pull request by dvdkruk**
See #8

### CODE REVIEW

**Comment by dvdkruk** [comment]
Created an implementation for generating protobuf schemas from POJO definitions, using the builder/model of ```protoparser```. It's not perfect but will do the job ;-).

**Comment by cowtowncoder** [comment]
Sounds great to me!

One thing before I go ahead and merge this: we need a Contributor License Agreement (CLA) before the first contribution. It's at:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement.pdf

and usually is easiest to print, fill+sign, scan and email to `info` at fasterxml dot com.
If you could do that (unless I've already asked for it -- sorry if so, we get many new contributors), I can go ahead and get the feature merged in. It's something I really want to see, so big thank you for doing this.

**Comment by dvdkruk** [comment]
@cowtowncoder I've made this feature on behalf of a big company, so it could take some time before the CLA is signed. However I think its highly possible that they accept the CLA, it only takes some time (big companies you know ;-)).

**Comment by cowtowncoder** [comment]
@dvdkruk If you are thinking of corporate CLA, you most likely then want CCLA, this one:

https://github.com/FasterXML/jackson/blob/master/contributor-agreement-corporate.txt

based on our past experience of getting it from 3 big corporations (they found something to dislike in individual CLA). Apologies for the hassle, but the other side of the coin is that the same companies also very much want some assurances of code getting it nice & clean. :-)
(for which CLAs work as an ok compromise)

No worries about time it takes, big wheels turn slow (alas). It'll be ready when it is ready etc.

**Comment by dvdkruk** [comment]
@cowtowncoder In the CLA and CCLA there is no statement about that we as a company/individuals cannot be held liable for possible damage that the usage of the contributed/donated code may bring and that we are in no way guarantee that the code will work. Is this true or is this defined somewhere else, in a different document? If this is not somewhere defined it is highly possible that the legal department will not accept the CLA/CCLA. We like more how it is done with Apache Software Foundation (ASF), where we give the ownership of our contributions/donations to the ASF.

**Comment by cowtowncoder** [comment]
@dvdkruk I can't comment much on that, beyond saying that CLA is a stand-alone document as far as I know; but that we license code under Apache License 2.0 which (I think) has such statements. I don't think such indemnification is something CLAs typically have.

I also know that big corporations have found the CCLA acceptable (but not the CLA). I can tell bit more offline if you are interested (my email is tsaloranta at google mail) outside of github issue, if that helps.

I am personally not against transfer of ownership if that is needed, but it is nice to have just a single workflow if possible. If not, we can discuss this further via `info` at fasterxml dot com, where Paul (the other part of fasterxml) can also chime in. I definitely would not want this to become a blocker for the great contribution.

**Comment by dvdkruk** [comment]
@cowtowncoder I see the mentioned statement in Apache License 2.0, so that is good. The CLA and CCLA are now at the legal department, and it will take some time before they are handled. Till that moment I leave this pull request open and will do future work on my fork. It's not ideal, but ok for the moment. When I have more information I will contact you.

**Comment by cowtowncoder** [comment]
@dvdkruk Thank you for going through this -- it's a PITA, but on plus side once it's done it need not be repeated.

Also note that you only need to do one or the other, not both. Based on past experience companies tend to favor CCLA one, but we are content with either one.

**Pull request merged**
